[package]
name = "rime-rs"
version = "0.1.0"
authors = ["zwPapEr"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[profile.dev]
rpath = true

[build-dependencies]
bindgen = "0.53.1"
